#!/usr/bin/env sh

# open terminal
riverctl map normal Super Return spawn foot

# close focused view
riverctl map normal Super W close

# exit river
riverctl map normal Super+Control Q exit

# focus next/previous views
riverctl map normal Super L focus-view next
riverctl map normal Super H focus-view previous

# swap views with next/previous view
riverctl map normal Super+Shift L swap next
riverctl map normal Super+Shift H swap previous

# focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# bump the focused view to the top of the layout stack
riverctl map normal Super+Control Return zoom

# decrease/increase the main ratio of rivertile(1)
riverctl map normal Super+Control H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Control L send-layout-cmd rivertile "main-ratio +0.05"

# increment/decrement the main count of rivertile(1)
riverctl map normal Super+Alt Period send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Alt Comma send-layout-cmd rivertile "main-count -1"

# move views
riverctl map normal Super+Alt H move left 150 
riverctl map normal Super+Alt J move down 150
riverctl map normal Super+Alt K move up 150
riverctl map normal Super+Alt L move right 150

# snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# resize views 
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# move views with mouse button
riverctl map-pointer normal Super BTN_LEFT move-view

# resize views with mouse button
riverctl map-pointer normal Super BTN_RIGHT resize-view

# toggle float with middle mouse button
# riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# toggle float
riverctl map normal Super F toggle-float

# toggle fullscreen
riverctl map normal Super M toggle-fullscreen

# change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# map volume keys
riverctl map normal None XF86AudioRaiseVolume spawn 'amixer set Master 5%+ && pkill -x -RTMIN+11 waybar' 
riverctl map normal None XF86AudioLowerVolume spawn 'amixer set Master 5%- && pkill -x -RTMIN+11 waybar'
riverctl map normal None XF86AudioMute        spawn 'amixer set Master
toggle'

# map media keys
riverctl map normal None XF86AudioPlay        spawn 'playerctl play-pause'
riverctl map normal None XF86AudioPrev        spawn 'playerctl previous'
riverctl map normal None XF86AudioNext        spawn 'playerctl next'

# map brightness keys
riverctl map normal None XF86MonBrightnessUp   spawn 'brightnessctl set +1%'
riverctl map normal None XF86MonBrightnessDown spawn 'brightnessctl set 1%-'

# set border color
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

# set keyboard repeat rate
riverctl set-repeat 110 210 

# follow focus on cursor
riverctl focus-follows-cursor normal

# cursor warp
riverctl set-cursor-warp on-output-change

# launcher
riverctl map normal Super R spawn 'cd ~/.local/bin/ && ./launcher'
riverctl map normal Super+Shift R spawn 'cd ~/.local/bin/ && ./launcher_run'

# launch applications
# riverctl map normal 

# autostart
riverctl spawn 'mako'
riverctl spawn 'wpaperd'
riverctl spawn 'waybar'

# set default layout
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

# scratchpads

# The scratchpad will live on an unused tag. Which tags are used depends on your
# config, but rivers default uses the first 9 tags.
scratch_tag=$((1 << 20 ))

# Toggle the scratchpad
riverctl map normal Super+Shift Return toggle-focused-tags ${scratch_tag}

# Send windows to the scratchpad with Super+Shift+P
riverctl map normal Super+Shift P set-view-tags ${scratch_tag}

# Set spawn tagmask to ensure new windows don't have the scratchpad tag unless
# explicitly set.
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ $scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}
